### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by danielkerstan** [nex-dcp30-intro/notebook#1]
accidentally created issues for tasks instead of subtasks; closed all of those issues

**Comment by danielkerstan** [comment]
## Task List

- [x] Exploration
  - [x] Find data set
  - [x] Explore data and possible use cases
  - [x] make slideshow
- [x] Download and cleaning
  - [x] Write code to read in and filter data
  - [x] Test data read in for binder
- [x] Data visualization
  - [x] Precipitation visualization
  - [x] Temperature visualization
- [x] Data analysis
  - [x] Time series
  - [x] Histogram
  - [x] Maps
- [x] Data applications
  - [x] Exploration of use cases
- [ ] Tutorial
  - [x] Configure binder
  - [ ] Practice
  - [ ] Presentation

**Comment by desik23** [comment]
created tasks v2 which supercedes this due to problems with converting subtasks to issues. please refer to this for milestones task.
